pgm_app/urls.py
from django.urls import path
from . import views
app_name = 'pgm_app'
urlpatterns = [
    path('', views.IndexListView.as_view(), name='index'),
    path('project/<slug:slug>/',views.ProjectDetailView.as_view(), name='project'),
]

pgmproject/urls.py
from django.contrib import admin
from django.urls import include, path
from django.views.generic import RedirectView
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('pgm_app.urls')),
    path('', RedirectView.as_view(url='', permanent=True)),
    path(
        "favicon.ico",
        RedirectView.as_view(url=settings.STATIC_URL + "/favicon.ico"),
    ),
]+ static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)+ static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

pgm_app/models.py
from django.db import models
# Create your models here.
class Project(models.Model):
    # Fields
    title = models.CharField(max_length=100, help_text="Titulo del Proyecto", verbose_name="Titulo")
    subtitle = models.CharField(max_length=100, blank=True, help_text="Subtitulo", verbose_name="Subtitulo")
    image = models.ImageField(upload_to='media/images',blank=True, help_text="Imagen del Proyecto", verbose_name="Imagen")
    slug = models.SlugField(max_length=100, help_text="No tocar", verbose_name="Slug")
    description = models.TextField(help_text="Descripcion del Proyecto", verbose_name="Descripcion")
    date = models.DateField()
    video_url = models.CharField(max_length=200, blank=True,help_text='Url del video ', verbose_name='Video URL')
    source = models.ForeignKey('Source', on_delete=models.CASCADE,blank=True, help_text='Youtube o Vimeo o NONE si no hay video',verbose_name='Source')
    category = models.ForeignKey('Category', on_delete=models.SET_NULL, null=True, help_text='Categoria del projecto', verbose_name='Categoria')
    # Metadata
    class Meta:
        ordering = ['-date','title']
        verbose_name = "Proyecto"
        verbose_name_plural = "Proyectos"
    # Methods
    def __str__(self):
        return f'{self.title}'
class ImageModel(models.Model):
    image = models.ImageField(upload_to='media/images', help_text='Imagen del Proyecto', verbose_name='Imagen')
    project = models.ForeignKey('Project', on_delete=models.CASCADE, help_text='Proyecto', verbose_name='Proyecto')
    class Meta:
        verbose_name = "Imagen"
        verbose_name_plural = "Imagenes"
    def __str__(self):
        return f'{self.image}'
class Category(models.Model):
    # Fields
    name = models.CharField(max_length=100, help_text="Nombre de la Categoria", verbose_name="Nombre")
    slug = models.SlugField(unique=True)
    # Metadata
    class Meta:
        verbose_name = "Categoria"
        verbose_name_plural = "Categorias"
    # Methods
    def __str__(self):
        return f'{self.name}'
class Source(models.Model):
    #Fields
    name = models.CharField(max_length=200,db_index=True, help_text='Youtube ou Vimeo', verbose_name='Nom du site')
    def __str__(self):
        return f'{self.name}'

pgm_app/views.py
from django.views import generic
from .models import Category, Project
# Create your views here.
class IndexListView(generic.ListView):
    template_name = 'index.html'
    context_object_name = 'projects_list'
    def get_queryset(self):
        return Project.objects.all().order_by('date')
    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['category_list'] = Category.objects.all().order_by('id')
        return context

class ProjectDetailView(generic.DetailView):
    model = Project
    template_name = 'project.html'

pgm_app/templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=yes" />
  <meta name="description" content="" />
  <meta name="author" content="" />
  <!-- Font Awesome icons (free version)-->
  <script src="https://use.fontawesome.com/releases/v6.1.0/js/all.js" crossorigin="anonymous"></script>
  <!-- Core theme CSS (includes Bootstrap)-->
  {% load static %}
  <title>{% block title %}PGM Art Productions{% endblock title%}</title>
  <link rel="icon" type="image/x-icon" href="{% static 'core/img/favicon.ico'%}" />
  {% comment %} fonts {% endcomment %}
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.googleapis.com" />
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
  <link href="https://fonts.googleapis.com/css2?family=Roboto+Condensed:wght@300&display=swap" rel="stylesheet" />
  <link href="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.3.0/mdb.min.css" rel="stylesheet" />
  <!-- Styles -->
  <link href="{% static 'core/css/base.css'%}" rel="stylesheet" />
  <!-- MDB -->
  {% block styles %} {% endblock styles %}
</head>

<body id="page-top">
  <!-- Navigation-->
  <!-- Navbar -->
  <nav class="navbar navbar-expand-lg navbar-dark bg-dark sticky-top" id="navbar">
    <!-- Container wrapper -->
    <div class="container-fluid">
      <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'pgm_app:index' %}#page-top">
        <img src="{% static 'core/img/favicon.ico' %}" height="60" alt="PGM Logo" loading="lazy" />
        <small>PGM Art Production <br />
          <p>Management culturel</p>
        </small>
      </a>
      <!-- Toggle button -->
      <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navigation"
        aria-controls="navigation" aria-expanded="false" aria-label="Toggle navigation">
        <i class="fas fa-bars"></i>
      </button>

      <!-- Collapsible wrapper -->
      <div class="collapse navbar-collapse" id="navigation">
        <!-- Navbar brand -->

        <!-- Left links -->
        <ul class="navbar-nav ms-auto mb-2 mb-lg-0">
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pgm_app:index' %}#page-top">Home</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pgm_app:index' %}#about">À propos de moi</a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pgm_app:index' %}#portfolio">Portfolio
            </a>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pgm_app:index' %}#news">Presse
            </a> 
          </li>
          <li class="nav-item">
            <a class="nav-link" href="{% url 'pgm_app:index' %}#contact">Contact</a>
          </li>
        </ul>
        <!-- Left links -->
      </div>
      <!-- Collapsible wrapper -->

      <!-- Right elements -->
    </div>
    <!-- Container wrapper -->
  </nav>

  {% block content %} {% endblock content %}

  <!-- Footer-->
  <footer class="footer bg-dark small text-center text-white-50" id="contact">
    <section class="socials">
      <br />
      <div class="contact-title">
        <h1>Contact</h1>
      </div>
      <div class="container socials-container">
        <a style="color: #3b5998" href="https://www.facebook.com/EscenicaTeatroMagico" role="button"><i
            class="fab fa-facebook-f fa-lg"></i></a>

        <!-- Instagram -->
        <a style="color: #ac2bac" href="https://www.instagram.com/escenica_teatro/" role="button"><i
            class="fab fa-instagram fa-lg"></i></a>

        <!-- Linked In -->
        <a style="color: #0082ca" href="https://www.linkedin.com/in/paloma-gordián-montalva-b663603a/" role="button"><i
            class="fab fa-linkedin-in fa-lg"></i></a>
      </div>
      <br />
      <div class="email-container">
        <i class="fas fa-envelope text-primary"> </i>
        <span>zgp.production@gmail.com</span>
      </div>
      <div class="container px-4 px-lg-5">
        Pgm Art Productions. <br />Web by Champulin
        <!-- Linked In -->
        <a style="color: #333333" href="https://github.com/Champulin/" role="button"><i
            class="fab fa-github fa-lg"></i></a>
      </div>
    </section>
  </footer>
  <!-- MDB -->
  <script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/mdb-ui-kit/4.3.0/mdb.min.js"></script>
  {% block scripts %} {% endblock scripts%}
</body>

</html>

pgm_app/templates/index.html
{% extends "base.html"%} {% load static %} {% block styles %}
<link href="{% static 'core/css/index.css' %}" rel="stylesheet" />
{% endblock styles %} {% block content %}
<main>
  <header>
    <!-- Background image -->
    <div id="hero-bg" class="p-5 text-center bg-image" style="background-image: url({% static 'core/img/home.jpg' %});">
      <div class="mask" style="background-color: rgba(0, 0, 0, 0.6)">
        <div class="d-flex justify-content-center align-items-center h-100">
          <div class="text-white">
            <h1 class="mb-3">PALOMA GORDIÁN MONTALVA</h1>
            <h4 class="mb-3">
              CRÉATION - ARTS VIVANTS - PROGRAMMATION - DÉVELOPPEMENT DE PROJETS
            </h4>
          </div>
        </div>
      </div>
    </div>
    <!-- Background image -->
  </header>
  <!-- About-->
  <section class="text-center" id="about">
    <div class="px-4 px-lg-5">
      <div class="row gx-4 gx-lg-5 justify-content-center">
        <div class="col-lg-8">
          <br />
          <h2 class="text-white mb-4">À propos de moi</h2>
          <br /><br />
          <div class="hero-pic">
            <img src="{% static 'core/img/about_pic.jpg' %}" class="img-fluid" alt="" />
          </div>
          <p>
            Je m'appelle Paloma Gordián Montalva, je suis communicatrice
            audiovisuelle de l'Université des Arts et Sciences de la
            Communication (UNIACC) de Santiago du Chili, dont je suis sortie
            diplômée en 2001.
            <br /><br />
            Depuis le début de ma carrière, mes intérêts se sont concentrés sur
            la création et la gestion de projets culturels et sur le
            perfectionnement de mes capacités en termes de gestion d’équipe, de
            production, de recherche de financements, de vente et marketing, de
            communication et de relation client. Dans mon expérience de
            communicant audiovisuel, mon passage à la télévision et au théâtre a
            été essentiel pour comprendre la relation entre produit, contenu et
            spectateur. En travaillant dans les services de marketing des
            principales chaînes de télévision chilienne, j’ai été amenée à
            concevoir et développer l’image de diverses entreprises, à élaborer
            des spots publicitaires, des campagnes politiques, des programmes
            pour enfants et des séries animées. Je me suis ensuite orientée vers
            le théâtre, en tant que productrice d’importantes compagnies
            théâtrales chiliennes, et j’ai travaillé également sur des projets
            culturels basés sur l’utilisation du multimédia.

            <br /><br />La relation étroite entre mon travail en gestion
            culturelle et la création artistique m’a conduite à me lancer
            moi-même dans une démarche créative, proposant et expérimentant
            d’autres médias et formats, tels que les nouvelles technologies et
            les arts visuels.
          </p>
        </div>
      </div>
    </div>
  </section>
  <!-- Projects -->
  <section class="portfolio-section" id="portfolio">
    <br />
    <br />
    <h1>PORTFOLIO</h1>
    <br />
    <br />
    <!-- Control buttons -->
    <div class="btn-toolbar btn-toolbar-sm flex-wrap" role="toolbar" aria-label="Basic example" id="myBtnContainer">
      <button type="button" class="btn btn-outline-primary boton active" onclick="filterSelection('all')" checked>
        Montrer Tout
      </button>
      {% for category in category_list %}
      <button type="button" class="btn btn-outline-primary boton" onclick="filterSelection('{{category.id}}')">
        {{category.name}}
      </button>
      {% endfor %}
    </div>
    <br />
    <br />
    <div class="row row-cols-1 row-cols-md-3 g-4" id="item-container">
      {% for project in projects_list %}
      <div class="col filterDiv {{project.category.id}}">
        <div class="card h-100">
          <a href="{% url 'pgm_app:project' slug=project.slug %}">
            <img src="{{project.image.url}}" class="card-img-top" alt="..." />
            <div class="card-body">
              <h5 class="card-title">{{project.title}}</h5>
            </div>
          </a>
          <p class="card-text">{{project.subtitle}}</p>
        </div>
      </div>
      {% endfor %}
    </div>
  </section>
  <!-- News Articles -->
  <section class="news-section" id="news">
    <br />
    <br />
    <h1>Presse</h1>
    <br />
    <br />
    <section class="content">
      <div class="item ratio ratio-16x9">
        <iframe src="https://www.youtube.com/embed/uLY1t5s8l7g" title="Papelucho Historiador" frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen></iframe>
      </div>
      <div class="item ratio ratio-16x9">
        <iframe src="https://www.youtube.com/embed/vDsoO6e5ov0" title="Dit la presse" frameborder="0"
          allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture"
          allowfullscreen></iframe>
      </div>
    </section>
  </section>
  <br />
</main>
{% endblock content %} {% block scripts %}
<script src="{% static 'core/js/index.js' %}"></script>
{% endblock scripts %}

pgm_app/templates/project.html
{% extends "base.html"%}
{% load static %}
{% block styles %}
<link href="{% static 'core/css/project_detail.css' %}"  rel="stylesheet" />
{% endblock styles %}
{% block content %}
<main>
    <section class="content"> 
        <div class="container">
            <div class="row">
                <div class="col-md-12">
                    <div class="project-detail">
                        <div class="project-detail-header">
                            <h1>{{project.title}}</h1>
                        </div>
                        <div class="project-detail-body">
                            <div class="row">
                                <div class="col-md-6">
                                    <div class="project-detail-body-left">
                                        <div class="project-detail-body-left-image">
                                            <img src="{{project.image.url}}" alt="">
                                        </div>
                                    </div>
                                </div>
                                <div class="col-md-6">
                                    <div class="project-detail-body-right">
                                        <div class="project-detail-body-right-content">
                                            <p>{{project.description}}</p>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
        <!-- VIDEO CONTAINER --> 
      {% if project.source.name != 'none' %} 
      <section class="video-container {{project.source}} ratio ratio-16x9">
        <section id="video-player"></section>
        </section>
      </section>
      {%endif%}
      <br />
      <!-- IMAGE CONTAINER -->
      <section class="row row-cols-1 row-cols-md-3 g-4" id="item-container">
        {% for i in project.imagemodel_set.all %}
        <img src="{{i.image.url}}" class="img-fluid" alt="">
        {% endfor %}
      </section>
      <br />
    </section>
</main>
{% endblock content %}
{% block scripts %}
<script>
    const url = "{{ project.video_url }}";
  </script>
  {% if project.source.name == "youtube" %}
  <script>
    var tag = document.createElement('script');
    tag.src = "https://www.youtube.com/iframe_api";
    var firstScriptTag = document.getElementsByTagName('script')[0];
    firstScriptTag.parentNode.insertBefore(tag, firstScriptTag);
    function getYoutubeId(url){
      const regExp = /^.*((youtu.be\/)|(v\/)|(\/u\/\w\/)|(embed\/)|(watch\?))\??v?=?([^#&?]*).*/;
      const match = url.match(regExp);
      return (match&&match[7].length==11)? match[7] : false;
    }
    const id = getYoutubeId(url);
    var player;
    function onYouTubeIframeAPIReady() {
      player = new YT.Player('video-player', {
        height: '100%',
        width: '100%',
        videoId: id,
        playerVars: { 'modestbranding': 1, 'rel': 0, 'controls': 1 },
      });
    }
  </script>
  {% endif %}
  
  {% if project.source.name == "vimeo" %}
  <script src="https://player.vimeo.com/api/player.js"></script>
  <script>
    const player = new Vimeo.Player('video-player', {
      url: url,
      responsive: true,
    });
  
    player.on('play', function() {});
    </script>
    {% endif %}
{% endblock scripts %}